"use client"
import Head from "next/head"
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { FaInstagram, FaLinkedin, FaGithub } from 'react-icons/fa';
import Image from "next/image";
import eu from '../public/images/eu.jpg';
import {  useState } from 'react';
import { GitHub, Facebook, Instagram, Linkedin } from "react-feather"
import IconButton from "../components/socialIcons"


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
      <title>{process.env.title}</title>
        <meta name="description" content="Generated by created" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10  dark:bg-gray-900">
        <section className=' min-h-screen'>
          <nav className="py-10 mb-12 flex justify-between ">
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-indigo-500 text-white px-4 py-2 rounded-md ml-8" href="https://github.com/KawanMark" target="_blank">Projects</a>
              </li>
            </ul>
          </nav>

          <div className="max-w-6xl mx-auto mt-6 shadow bg-slate-50 rounded-md  py-6 px-4 sm:px-12 dark:bg-gray-800">
            <div className="flex mt-2 items-center justify-items-center justify-center flex-col sm:flex-row">
              <div className="relative w-52 h-52 ">
                <Image className="rounded-full" layout="fill" src={eu} alt="Minha Foto" objectFit="cover"/>
              </div>
            </div>
          </div>


          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-indigo-800">Kawan Mark</h2>
            <h3 className="text-2xl py-2 dark:text-white"> Software Engineer | FEI Computer Scientist</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white"> As a Computer Science student, I have a strong interest in programming, software development and Cybersecurity. Currently a member and monitor of the Programming Marathon by FEI, in which I teach low-level programming for competitors and carry out algorithm development. I'm always looking to improve my skills and learn more about recent technologies, in addition to keeping up with market trends.</p>
          </div>
            <h1 className="flex justify-center text-gray-700 font-medium mb-8 text-3xl dark:text-white">Checkout My Socials</h1>

          <div className=" flex justify-center px-4 mb-0">
              <IconButton text="Github" link="https://github.com/KawanMark" color="bg-gray-600">
                <GitHub size={20} />
              </IconButton>
              <IconButton
                text="Instagram"
                color="bg-gradient-to-tr from-yellow-500 to-purple-500 via-pink-500"
                link="https://www.instagram.com/kaw.mark/"
              >
                  <Instagram size={20} />
                </IconButton>
              <IconButton text="Linkedin" color="bg-blue-800" link="https://www.linkedin.com/in/kawan-mark-656825162/">
                <Linkedin size={20} />
              </IconButton>
          </div>

        </section>



      </main>
    </div>
  )
}
